# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  # You may remove this if you don't use go modules.
  - go mod download
  # you may remove this if you don't need go generate
  - go generate ./...
builds:
- main: ./
  env:
  - CGO_ENABLED=0
  binary: cherryctl
  ldflags:
   - -X github.com/cherryservers/cherryctl/cmd.Version={{.Version}}
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: windows
    goarch: 'arm64'

archives:
- format: binary
  name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews: 
- homepage: "https://www.cherryservers.com/"
  description: "Official Cherry Servers CLI"
  license: "MIT"
  dependencies:
  - name: "go"
    type: build
  test: |
    system "#{bin}/cherryctl -v"
  commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
  repository:
    owner: cherryservers
    name: homebrew-cherryctl
    # https://goreleaser.com/errors/resource-not-accessible-by-integration/
    token: "{{ .Env.TAP_TOKEN }}"